# Generated by Django 3.0.5 on 2020-05-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20200514_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(blank=True, default='media/audio/default.jpg', upload_to='audio/'),
        ),
    ]
