# Generated by Django 3.0.5 on 2020-05-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_auto_20200514_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(blank=True, default='audio/default.jpg', upload_to='audio/'),
        ),
    ]
