# Generated by Django 3.0.5 on 2020-05-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_auto_20200514_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.ImageField(blank=True, default='audio/default.jpg', upload_to='images/'),
        ),
    ]
