# Generated by Django 3.0.5 on 2020-05-14 17:00

from django.db import migrations, models
import music.validators


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_auto_20200514_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.ImageField(blank=True, default='audio/default.jpg', upload_to='images/', validators=[music.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(blank=True, default='audio/default.jpg', upload_to='audio/', validators=[music.validators.validate_audio_extension]),
        ),
    ]
