language: python
python:    
  - "3.7"
  - "3.8"

install:
  - pip install -r requirements_build.txt

before_script:
  - cp .env.example .env
  - python manage.py test music.tests
script:
  - python manage.py migrate