# Generated by Django 3.0 on 2019-12-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebTune', '0003_auto_20191220_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.ImageField(blank=True, upload_to='=logos/'),
        ),
    ]
