# Generated by Django 3.0.2 on 2020-04-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebTune', '0004_auto_20191220_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='file_type',
        ),
        migrations.AddField(
            model_name='song',
            name='song_file',
            field=models.FileField(blank=True, upload_to='mp3/'),
        ),
    ]
